### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by bitsurfr** [grafana/google-sheets-datasource#90]
Hi, the Google Sheets data source does not seem to run on ARM machines. I discovered this when I was troubleshooting the "Metric request error" when trying to show sheets based data. 

From the grafana logs:

During startup:
t=2020-05-06T04:13:32+0000 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=grafana-googlesheets-datasource error="fork/exec /var/lib/grafana/plugins/grafana-googlesheets-datasource/dist/gfx_sheets_linux_arm: no such file or directory"

When accessing a dashboard:
t=2020-05-06T04:05:21+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: grafana-googlesheets-datasource" remote_addr=[]

Thanks!

**Comment by dietah** [comment]
After some late night fiddling around I was able to build the plugin for arm. I got it working to the point where I could select which shared sheet should be used but got stuck after that. (it showed an autocomplete dropdown after a couple of seconds)

![dropdown](https://i.imgur.com/dXCzKUq.png "dropdown")

After selecting the sheet and trying to fetch data, it outputs a "exit status 2" after handling the grpc stream and I cannot figure out why it is causing the error, so I gave up 😔

Also as a side note, if someone else wants to try and build the backend part themselves, using yarn and mage is quite overkill. After you have golang installed you can simply use
`env GOOS=linux GOARCH=arm go build -o dist/gfx_sheets_linux_arm -tags netgo -ldflags -w ./pkg` (building on your pi or similar arm device ofc)

I did modify the `go.mod` file to make sure the grpc version was the same [grafana-plugin-sdk-go](https://github.com/grafana/grafana-plugin-sdk-go/blob/master/go.mod) as I thought that would solve the issue:
```
replace (
    google.golang.org/grpc => google.golang.org/grpc v1.27.1
)
```

Maybe it can help someone that is better at golang than me 😅

**Comment by zoltanbedi** [comment]
v1.1.2 now has arm build.

**Comment by AMG-91** [comment]
Hi!
I was testing the Google Sheets plugin but it doesn't work for me as I get the message error "Plugin health chech failed" when I try to configure the DataSource with the generated Google Cloud Platform API Keys.
I think the error is related to the fact that I am using Grafana on an RPi 4 model B (armv71) because I have tried the same plugin in an installation on windows and it has worked perfectly.
I would greatly appreciate if someone of the community or Grafana Team (maybe @zoltanbedi ) could help me get the plugin to work on my RPi.
Thanks a lot for everything

**Comment by zoltanbedi** [comment]
Hi @AMG-91,
I'm not sure if it is related to that but what you can try is to build the plugin locally and use that. https://grafana.com/docs/grafana/latest/administration/configuration/#plugins

**Comment by AMG-91** [comment]
Thanks for the answer @zoltanbedi . Yes, as I mentioned in a local installation on windows, the connection with Sheets has worked perfectly but I needed to do the same on RPi 4. Isn't it possible? If so, could it be included in the next plugin update?
Thanks a lot

**Comment by zoltanbedi** [comment]
Pushing the ARM64 is not something that we are actively working on right now so I would say that this is not going to be supported in the near future. Sorry.

Your best bet is still building the plugin yourself.

**Comment by alexmarkley** [comment]
Hey, @zoltanbedi I realize you just said you're not actively working on this.

I did want to inform you that this issue is present in AWS on Graviton / Graviton2 arm64 EC2 instances. I'm planning on building the plugin for myself to work around the issue, but it may be a blocker for other folks who are trying to run on Graviton.

Thanks!

**Comment by zoltanbedi** [comment]
Thanks for the heads up. It looks like that we will pick this up sooner.

**Comment by AMG-91** [comment]
Great news😀! I just updated the version of the plugin (and Grafana) and everything works perfectly. Now it has been possible to connect to Spreadsheet and I see all the data stored.  You have saved me from the problem I had. Thank you so much everyone! 😉

**Comment by alexmarkley** [comment]
:+1: I can confirm my AWS Graviton installation of Grafana now works with the official build of google-sheets-datasource. Thanks @zoltanbedi for making this update!
